// The Hidden Archive -- Full 256-card set
// [name, type, cost, power, toughness, keyword, abilityText, flavor]
const CARD_DATA = [
  ['The Voynich Cipher Club', 'group', 1, 2, 2, 'Cover', "Spend 1 Influence: remove Exposed from one of your Groups.", "It's just a coincidence, repeated a suspicious number of times."],
  ['Nordic Aliens', 'operation', 1, 0, 0, '', "Target Group becomes Exposed.", "Somewhere in the desert, something hums at night."],
  ['D.B. Cooper\'s Escape', 'group', 2, 1, 3, '', "No additional ability.", "It's just a coincidence, repeated a suspicious number of times."],
  ['No Such Agency', 'operation', 2, 0, 0, '', "Look at the top 2 cards of your deck. Add 1 to hand, Archive the rest.", "It never happened. There's a memo confirming that."],
  ['Antigravity Craft Rumor', 'wildcard', 6, 6, 6, '', "Dual-use: discard face-down for +1 Network Die (max 10), or recruit face-up as a weak Group.", "One giant leap, and a thousand unanswered questions."],
  ['Chupacabra', 'wildcard', 1, 1, 1, '', "Dual-use: discard face-down for +1 Network Die (max 10), or recruit face-up as a weak Group.", "Cast a print in the mud and the story writes itself."],
  ['Deep State', 'group', 2, 3, 3, '', "When recruited, gain 1 Influence.", "Approved in a room with no windows."],
  ['Phoenix Lights', 'group', 3, 3, 3, 'Pierce', "Excess combat damage carries over to the opponent's Life.", "Somewhere in the desert, something hums at night."],
  ['Crop Circles', 'group', 2, 3, 4, '', "No additional ability.", "The truth is filed under a redaction."],
  ['Bohemian Grove', 'wildcard', 1, 1, 1, '', "Dual-use: discard face-down for +1 Network Die (max 10), or recruit face-up as a weak Group.", "Membership is by invitation. Existence is by denial."],
  ['Hollow Earth', 'group', 2, 3, 3, 'Network', "When recruited, draw 1 card.", "Lost, sunken, and somehow still on three separate maps."],
  ['Project Mockingbird Handler', 'group', 5, 5, 6, 'Expose', "When this deals combat damage, the opposing Group involved becomes Exposed.", "Somewhere there's a form for this. You'll never see it."],
  ['Vanishing Apollo Footage', 'operation', 4, 0, 0, '', "Look at an opponent's hand. Discard 1 card from it at random.", "One giant leap, and a thousand unanswered questions."],
  ['Wellness Grift Empire', 'group', 1, 1, 1, 'Pierce', "Excess combat damage carries over to the opponent's Life.", "The side effects are listed. The real ones aren't."],
  ['Holy Grail Quest', 'group', 3, 3, 4, '', "No additional ability.", "Older than the story that explains it."],
  ['HAARP', 'wildcard', 1, 1, 1, '', "Dual-use: discard face-down for +1 Network Die (max 10), or recruit face-up as a weak Group.", "Approved in a room with no windows."],
  ['The Aurora Aircraft Program', 'operation', 1, 0, 0, '', "Gain 1 Influence this turn only.", "The footage looks fake because it's old, not because it's fake. Probably."],
  ['Continuity of Government', 'group', 1, 2, 1, 'Expose', "When this deals combat damage, the opposing Group involved becomes Exposed.", "It never happened. There's a memo confirming that."],
  ['Central Bank Digital Currency', 'operation', 5, 0, 0, '', "Look at an opponent's hand. Discard 1 card from it at random.", "Money is just a story everyone agreed to believe."],
  ['Classified Weather Modification', 'group', 2, 3, 4, 'Cover', "Spend 1 Influence: remove Exposed from one of your Groups.", "Somewhere there's a form for this. You'll never see it."],
  ['Operation Northwoods', 'group', 2, 2, 3, 'Haste', "Can attack the turn it's recruited.", "Approved in a room with no windows."],
  ['Big Dairy Lobby', 'group', 5, 5, 6, 'Expose', "When this deals combat damage, the opposing Group involved becomes Exposed.", "Somebody patented the thing that was already free."],
  ['Face Recognition Grid', 'group', 2, 2, 2, '', "When recruited, gain 1 Influence.", "It never happened. There's a memo confirming that."],
  ['Baalbek\'s Foundation Stones', 'group', 3, 3, 3, '', "When recruited, gain 1 Influence.", "Buried for a reason nobody remembers, which is the point."],
  ['Breakaway Civilization', 'referendum', 2, 0, 0, '', "Referendum. Each player votes (weight = Groups in play). If you win a majority, the player with the most Groups skips their next Network Die gain.", "The footage looks fake because it's old, not because it's fake. Probably."],
  ['The Sunken Temple', 'group', 4, 4, 4, '', "When recruited, target opponent discards 1 card.", "Lost, sunken, and somehow still on three separate maps."],
  ['Necronomicon Fragment', 'wildcard', 3, 3, 3, '', "Dual-use: discard face-down for +1 Network Die (max 10), or recruit face-up as a weak Group.", "Older than the story that explains it."],
  ['Priory of Sion', 'operation', 6, 0, 0, '', "Look at an opponent's hand. Discard 1 card from it at random.", "Every handshake means something, to someone."],
  ['Giants of Old', 'group', 5, 5, 6, 'Haste', "Can attack the turn it's recruited.", "Older than the story that explains it."],
  ['Planet X', 'group', 4, 4, 5, '', "When recruited, gain 1 Influence.", "One giant leap, and a thousand unanswered questions."],
  ['Lizard People', 'referendum', 4, 0, 0, '', "Referendum. Each player votes (weight = Groups in play). If you win a majority, the player with the most Life discards a card.", "The woods keep their own secrets."],
  ['Location Data Broker', 'group', 4, 5, 4, '', "No additional ability.", "The algorithm didn't choose this for you. Someone chose the algorithm."],
  ['Denver Airport Murals', 'group', 5, 4, 7, '', "When recruited, draw 1 card.", "It's just a coincidence, repeated a suspicious number of times."],
  ['Ancient Library of Alexandria Rumor', 'group', 3, 3, 5, '', "When recruited, draw 1 card.", "Lost, sunken, and somehow still on three separate maps."],
  ['Dark Pool Trading Desk', 'group', 3, 2, 5, '', "When recruited, target opponent discards 1 card.", "Nobody elected the people who set the rate."],
  ['Inner Circle Compact', 'operation', 2, 0, 0, '', "Remove Exposed from up to 2 of your Groups.", "They meet in the room that isn't on the floor plan."],
  ['Petro-Yuan Rumor', 'group', 1, 2, 2, '', "When recruited, draw 1 card.", "Money is just a story everyone agreed to believe."],
  ['Shadow Banking Network', 'group', 2, 1, 2, '', "When recruited, gain 1 Influence.", "The bailout was quiet. The bill wasn't."],
  ['Shadow Cabinet', 'group', 2, 2, 2, 'Haste', "Can attack the turn it's recruited.", "Every handshake means something, to someone."],
  ['Contactee Circuit', 'group', 2, 1, 3, '', "No additional ability.", "The truth is filed under a redaction."],
  ['Social Credit Rollout', 'operation', 2, 0, 0, '', "All players lose 1 Life.", "Somewhere there's a form for this. You'll never see it."],
  ['Solar Warden Fleet', 'group', 3, 3, 4, 'Network', "When recruited, draw 1 card.", "Somewhere past the ice wall, the map just stops."],
  ['Mu the Lost Continent', 'wildcard', 1, 1, 1, '', "Dual-use: discard face-down for +1 Network Die (max 10), or recruit face-up as a weak Group.", "Older than the story that explains it."],
  ['Melon Heads Legend', 'group', 2, 3, 2, '', "When recruited, target opponent discards 1 card.", "The woods keep their own secrets."],
  ['Cattle Mutilation Reports', 'group', 4, 4, 4, 'Fortify', "Prevent the first 2 damage this group would take.", "Somewhere in the desert, something hums at night."],
  ['Flatwoods Monster', 'group', 2, 3, 2, '', "When recruited, gain 1 Influence.", "Cast a print in the mud and the story writes itself."],
  ['Beast of Gévaudan', 'group', 3, 3, 5, '', "No additional ability.", "Somewhere between folklore and fact, it walks."],
  ['Round Table Group', 'operation', 1, 0, 0, '', "Draw 3 cards.", "Every handshake means something, to someone."],
  ['Lemuria', 'group', 3, 3, 5, 'Haste', "Can attack the turn it's recruited.", "Older than the story that explains it."],
  ['Georgia Guidestones', 'group', 4, 3, 5, '', "When recruited, target opponent discards 1 card.", "Somebody noticed. Nobody could unsee it after that."],
  ['Paul Is Dead Rumor', 'group', 4, 5, 5, 'Expose', "When this deals combat damage, the opposing Group involved becomes Exposed.", "It's just a coincidence, repeated a suspicious number of times."],
  ['Social Media Shadowban', 'group', 5, 6, 5, '', "No additional ability.", "The algorithm didn't choose this for you. Someone chose the algorithm."],
  ['Yeti Expedition', 'group', 3, 3, 3, '', "When recruited, gain 1 Influence.", "Cast a print in the mud and the story writes itself."],
  ['The Hidden Hand', 'group', 3, 4, 4, '', "No additional ability.", "They meet in the room that isn't on the floor plan."],
  ['Numbered Swiss Account', 'operation', 2, 0, 0, '', "Remove Exposed from up to 1 of your Groups.", "The bailout was quiet. The bill wasn't."],
  ['Cheyenne Mountain Complex', 'group', 5, 5, 6, 'Pierce', "Excess combat damage carries over to the opponent's Life.", "Funded, denied, and buried under three other budgets."],
  ['Shambhala', 'group', 2, 1, 4, '', "When recruited, draw 1 card.", "Buried for a reason nobody remembers, which is the point."],
  ['Ancient Astronaut Theory', 'group', 3, 3, 5, '', "No additional ability.", "Lost, sunken, and somehow still on three separate maps."],
  ['The Wellness Retreat Circuit', 'group', 3, 3, 4, '', "When recruited, gain 1 Influence.", "The side effects are listed. The real ones aren't."],
  ['The Aurora Encounter', 'group', 2, 3, 2, 'Cover', "Spend 1 Influence: remove Exposed from one of your Groups.", "Every light in the sky has a witness and a denial."],
  ['Roswell Incident', 'operation', 2, 0, 0, '', "Look at the top 1 cards of your deck. Add 1 to hand, Archive the rest.", "Contact was made. Contact was covered up."],
  ['Rosicrucians', 'referendum', 4, 0, 0, '', "Referendum. Each player votes (weight = Groups in play). If you win a majority, reveal all hands.", "Membership is by invitation. Existence is by denial."],
  ['Alien Autopsy Footage', 'group', 4, 5, 4, 'Haste', "Can attack the turn it's recruited.", "They came in peace. Allegedly."],
  ['Big Ag Lobby', 'group', 6, 5, 6, '', "When recruited, gain 1 Influence.", "Cure it and there's no repeat customer."],
  ['Space Force Secrets', 'wildcard', 2, 2, 2, '', "Dual-use: discard face-down for +1 Network Die (max 10), or recruit face-up as a weak Group.", "One giant leap, and a thousand unanswered questions."],
  ['Lost Colony of Roanoke', 'group', 6, 6, 7, '', "No additional ability.", "The mural doesn't explain itself. That's the point of murals."],
  ['Kryptos Sculpture Code', 'wildcard', 2, 2, 2, '', "Dual-use: discard face-down for +1 Network Die (max 10), or recruit face-up as a weak Group.", "Somebody noticed. Nobody could unsee it after that."],
  ['Hopkinsville Goblin', 'group', 3, 3, 4, 'Expose', "When this deals combat damage, the opposing Group involved becomes Exposed.", "Somewhere between folklore and fact, it walks."],
  ['Patented Sunlight', 'operation', 5, 0, 0, '', "Look at the top 3 cards of your deck. Add 1 to hand, Archive the rest.", "Somebody patented the thing that was already free."],
  ['FEMA Camps', 'operation', 2, 0, 0, '', "Target Group becomes Exposed.", "Funded, denied, and buried under three other budgets."],
  ['Reptilians', 'operation', 6, 0, 0, '', "Gain 3 Influence this turn only.", "Cast a print in the mud and the story writes itself."],
  ['Classified Above Top Secret', 'group', 3, 3, 4, '', "No additional ability.", "Funded, denied, and buried under three other budgets."],
  ['Cicada 3301 Puzzle', 'group', 5, 6, 7, '', "When recruited, gain 1 Influence.", "Somebody noticed. Nobody could unsee it after that."],
  ['Lab-Grown Everything', 'group', 6, 7, 7, '', "When recruited, target opponent discards 1 card.", "Somebody patented the thing that was already free."],
  ['Foo Fighter Sightings', 'group', 2, 3, 2, '', "No additional ability.", "The truth is filed under a redaction."],
  ['Browser Fingerprinting', 'operation', 1, 0, 0, '', "Remove Exposed from up to 2 of your Groups.", "It's not listening. It's just very, very good at guessing."],
  ['MK-Ultra', 'wildcard', 2, 2, 2, '', "Dual-use: discard face-down for +1 Network Die (max 10), or recruit face-up as a weak Group.", "Approved in a room with no windows."],
  ['Sealed Indictment Cache', 'operation', 4, 0, 0, '', "Look at the top 3 cards of your deck. Add 1 to hand, Archive the rest.", "Approved in a room with no windows."],
  ['Kecksburg Object', 'group', 3, 2, 3, '', "When recruited, gain 1 Influence.", "Every light in the sky has a witness and a denial."],
  ['The Illuminati', 'group', 3, 4, 3, '', "No additional ability.", "Every handshake means something, to someone."],
  ['Sasquatch Footprint Cast', 'operation', 5, 0, 0, '', "Look at the top 3 cards of your deck. Add 1 to hand, Archive the rest.", "Blurry photo. Certain believer. No body ever found."],
  ['The Order of Nine', 'group', 2, 2, 2, '', "When recruited, gain 1 Influence.", "They meet in the room that isn't on the floor plan."],
  ['Max Headroom Broadcast Hijack', 'group', 1, 2, 1, '', "No additional ability.", "It's just a coincidence, repeated a suspicious number of times."],
  ['Sealed Grand Jury Files', 'operation', 1, 0, 0, '', "Remove Exposed from up to 3 of your Groups.", "Somewhere there's a form for this. You'll never see it."],
  ['World Economic Forum', 'group', 4, 3, 6, 'Cover', "Spend 1 Influence: remove Exposed from one of your Groups.", "The bailout was quiet. The bill wasn't."],
  ['Dark Fleet Program', 'group', 1, 1, 1, '', "No additional ability.", "One giant leap, and a thousand unanswered questions."],
  ['The Doomsday Plane', 'operation', 4, 0, 0, '', "Target player discards 3 cards.", "Funded, denied, and buried under three other budgets."],
  ['Nazca Lines', 'group', 1, 1, 2, '', "When recruited, draw 1 card.", "Every light in the sky has a witness and a denial."],
  ['Bilderberg Group', 'group', 3, 2, 4, '', "No additional ability.", "Membership is by invitation. Existence is by denial."],
  ['The Face on Mars', 'group', 5, 5, 7, '', "When recruited, target opponent discards 1 card.", "The footage looks fake because it's old, not because it's fake. Probably."],
  ['Project Blue Book', 'group', 3, 3, 3, '', "No additional ability.", "The truth is filed under a redaction."],
  ['Vimanas of the Vedas', 'operation', 5, 0, 0, '', "All players lose 1 Life.", "Contact was made. Contact was covered up."],
  ['The Voynich Manuscript', 'operation', 4, 0, 0, '', "Look at the top 3 cards of your deck. Add 1 to hand, Archive the rest.", "Older than the story that explains it."],
  ['Skinwalker Ranch', 'group', 3, 4, 4, '', "When recruited, draw 1 card.", "The woods keep their own secrets."],
  ['Mandela Effect', 'group', 2, 2, 4, 'Pierce', "Excess combat damage carries over to the opponent's Life.", "It's just a coincidence, repeated a suspicious number of times."],
  ['Operation Gladio', 'operation', 4, 0, 0, '', "Gain 3 Influence this turn only.", "Somewhere there's a form for this. You'll never see it."],
  ['Hedge Fund Backchannel', 'group', 1, 2, 2, '', "When recruited, gain 1 Influence.", "The bailout was quiet. The bill wasn't."],
  ['Quiet Bailout Fund', 'group', 5, 6, 6, 'Pierce', "Excess combat damage carries over to the opponent's Life.", "Nobody elected the people who set the rate."],
  ['The Cabal', 'group', 1, 1, 2, 'Cover', "Spend 1 Influence: remove Exposed from one of your Groups.", "Membership is by invitation. Existence is by denial."],
  ['The Toynbee Tiles', 'group', 2, 2, 2, '', "When recruited, draw 1 card.", "It's just a coincidence, repeated a suspicious number of times."],
  ['Essential Oil Cartel', 'group', 1, 2, 2, '', "When recruited, target opponent discards 1 card.", "Somebody patented the thing that was already free."],
  ['The Quiet Consortium', 'group', 5, 5, 5, '', "When recruited, target opponent discards 1 card.", "Membership is by invitation. Existence is by denial."],
  ['Offshore Shell Network', 'group', 1, 1, 1, 'Pierce', "Excess combat damage carries over to the opponent's Life.", "The bailout was quiet. The bill wasn't."],
  ['Nan Madol\'s Origins', 'operation', 2, 0, 0, '', "Return one Group from your Archive to your hand.", "Lost, sunken, and somehow still on three separate maps."],
  ['The Bond Market Whisper', 'wildcard', 3, 3, 3, '', "Dual-use: discard face-down for +1 Network Die (max 10), or recruit face-up as a weak Group.", "The bailout was quiet. The bill wasn't."],
  ['The Berenstain Bears Shift', 'operation', 2, 0, 0, '', "Gain 1 Influence this turn only.", "Somebody noticed. Nobody could unsee it after that."],
  ['Alien Abduction Ring', 'group', 2, 3, 2, 'Expose', "When this deals combat damage, the opposing Group involved becomes Exposed.", "Somewhere in the desert, something hums at night."],
  ['Agartha', 'group', 2, 2, 2, 'Pierce', "Excess combat damage carries over to the opponent's Life.", "Older than the story that explains it."],
  ['Knights Templar', 'group', 4, 4, 4, '', "When recruited, draw 1 card.", "Membership is by invitation. Existence is by denial."],
  ['Ark of the Covenant', 'wildcard', 5, 5, 5, '', "Dual-use: discard face-down for +1 Network Die (max 10), or recruit face-up as a weak Group.", "Lost, sunken, and somehow still on three separate maps."],
  ['Simulation Theory', 'group', 3, 4, 5, '', "No additional ability.", "Somebody noticed. Nobody could unsee it after that."],
  ['Stargate Project', 'group', 3, 3, 5, 'Fortify', "Prevent the first 2 damage this group would take.", "Funded, denied, and buried under three other budgets."],
  ['Chiles UFO Wave', 'group', 1, 2, 2, 'Network', "When recruited, draw 1 card.", "Somewhere in the desert, something hums at night."],
  ['Project Horizon Moonbase', 'group', 2, 1, 4, '', "When recruited, gain 1 Influence.", "Somewhere past the ice wall, the map just stops."],
  ['PRISM Data Feed', 'operation', 5, 0, 0, '', "Target player discards 3 cards.", "It never happened. There's a memo confirming that."],
  ['The Man on the Grassy Knoll', 'group', 5, 6, 6, '', "When recruited, draw 1 card.", "The mural doesn't explain itself. That's the point of murals."],
  ['Nutraceutical Loophole', 'operation', 1, 0, 0, '', "Draw 1 card.", "The side effects are listed. The real ones aren't."],
  ['Betty and Barney Case', 'group', 1, 2, 1, 'Expose', "When this deals combat damage, the opposing Group involved becomes Exposed.", "Somewhere in the desert, something hums at night."],
  ['Dugway Proving Ground', 'operation', 2, 0, 0, '', "Remove Exposed from up to 2 of your Groups.", "It never happened. There's a memo confirming that."],
  ['The Plunge Protection Team', 'group', 3, 4, 5, '', "When recruited, target opponent discards 1 card.", "Money is just a story everyone agreed to believe."],
  ['Men in Green', 'group', 2, 1, 3, '', "When recruited, gain 1 Influence.", "Every light in the sky has a witness and a denial."],
  ['Redacted Senate Testimony', 'group', 1, 1, 1, '', "When recruited, target opponent discards 1 card.", "Funded, denied, and buried under three other budgets."],
  ['Missing Time Report', 'operation', 1, 0, 0, '', "Return one Group from your Archive to your hand.", "It's just a coincidence, repeated a suspicious number of times."],
  ['Gene Therapy Panic', 'group', 5, 5, 5, '', "When recruited, target opponent discards 1 card.", "Somebody patented the thing that was already free."],
  ['The Fourteenth Amendment Clause', 'group', 5, 6, 5, '', "When recruited, draw 1 card.", "Funded, denied, and buried under three other budgets."],
  ['Area 51', 'group', 3, 3, 3, '', "When recruited, target opponent discards 1 card.", "They came in peace. Allegedly."],
  ['Doorbell Camera Network', 'operation', 1, 0, 0, '', "All players lose 1 Life.", "It's not listening. It's just very, very good at guessing."],
  ['Cashless Society Agenda', 'group', 3, 3, 3, 'Network', "When recruited, draw 1 card.", "The bailout was quiet. The bill wasn't."],
  ['The Understudy Theory', 'operation', 3, 0, 0, '', "Gain 1 Influence this turn only.", "The mural doesn't explain itself. That's the point of murals."],
  ['The Sphinx\'s Hidden Chamber', 'group', 4, 4, 6, 'Network', "When recruited, draw 1 card.", "Lost, sunken, and somehow still on three separate maps."],
  ['Water Fluoridation Push', 'operation', 2, 0, 0, '', "Draw 3 cards.", "The side effects are listed. The real ones aren't."],
  ['Montauk Project', 'group', 2, 1, 3, '', "When recruited, target opponent discards 1 card.", "Somebody noticed. Nobody could unsee it after that."],
  ['Shadow Profile Database', 'group', 5, 5, 5, 'Haste', "Can attack the turn it's recruited.", "Free to use means someone else is the product."],
  ['Project Sign', 'group', 2, 3, 4, 'Haste', "Can attack the turn it's recruited.", "The truth is filed under a redaction."],
  ['Men in Black', 'group', 5, 6, 6, '', "When recruited, draw 1 card.", "Every light in the sky has a witness and a denial."],
  ['Goatman of Maryland', 'wildcard', 1, 1, 1, '', "Dual-use: discard face-down for +1 Network Die (max 10), or recruit face-up as a weak Group.", "Somewhere between folklore and fact, it walks."],
  ['Project Camelot', 'operation', 1, 0, 0, '', "Draw 3 cards.", "It never happened. There's a memo confirming that."],
  ['Cover Band Conspiracy', 'group', 3, 3, 4, '', "When recruited, draw 1 card.", "The mural doesn't explain itself. That's the point of murals."],
  ['Interest Rate Cabal', 'operation', 1, 0, 0, '', "Target Group becomes Exposed.", "Nobody elected the people who set the rate."],
  ['Ordo Templi Society', 'operation', 1, 0, 0, '', "Target player discards 3 cards.", "They meet in the room that isn't on the floor plan."],
  ['The Recommendation Engine', 'group', 3, 4, 3, '', "When recruited, gain 1 Influence.", "The algorithm didn't choose this for you. Someone chose the algorithm."],
  ['Time Travel Program', 'group', 3, 3, 3, 'Expose', "When this deals combat damage, the opposing Group involved becomes Exposed.", "The mural doesn't explain itself. That's the point of murals."],
  ['Bigfoot Sighting', 'group', 3, 4, 5, '', "No additional ability.", "Cast a print in the mud and the story writes itself."],
  ['Bermuda Triangle', 'group', 4, 5, 4, '', "When recruited, draw 1 card.", "The mural doesn't explain itself. That's the point of murals."],
  ['Hangar 18', 'group', 2, 2, 3, '', "When recruited, target opponent discards 1 card.", "Contact was made. Contact was covered up."],
  ['The Taos Hum', 'group', 3, 3, 4, '', "When recruited, draw 1 card.", "It's just a coincidence, repeated a suspicious number of times."],
  ['The Nibiru Cataclysm', 'group', 3, 4, 4, '', "When recruited, gain 1 Influence.", "Somewhere past the ice wall, the map just stops."],
  ['Echelon Signals Network', 'group', 4, 5, 4, 'Haste', "Can attack the turn it's recruited.", "It never happened. There's a memo confirming that."],
  ['Continuity of Operations Bunker', 'group', 2, 3, 2, '', "When recruited, gain 1 Influence.", "Funded, denied, and buried under three other budgets."],
  ['Sunken City of Dwarka', 'group', 2, 1, 4, '', "When recruited, gain 1 Influence.", "Lost, sunken, and somehow still on three separate maps."],
  ['Petrodollar System', 'operation', 2, 0, 0, '', "Target Group becomes Exposed.", "The bailout was quiet. The bill wasn't."],
  ['The Antikythera Device', 'group', 4, 5, 4, '', "When recruited, gain 1 Influence.", "Older than the story that explains it."],
  ['Doppelganger Sighting', 'group', 2, 1, 4, '', "When recruited, target opponent discards 1 card.", "It's just a coincidence, repeated a suspicious number of times."],
  ['The Basel Accord Loophole', 'wildcard', 5, 5, 5, '', "Dual-use: discard face-down for +1 Network Die (max 10), or recruit face-up as a weak Group.", "The bailout was quiet. The bill wasn't."],
  ['Black Budget Division', 'group', 4, 4, 4, '', "When recruited, gain 1 Influence.", "Approved in a room with no windows."],
  ['Opioid Distribution Chain', 'referendum', 3, 0, 0, '', "Referendum. Each player votes (weight = Groups in play). If you win a majority, the player with the most Groups skips their next Network Die gain.", "The side effects are listed. The real ones aren't."],
  ['Mockingbird Media Network', 'operation', 6, 0, 0, '', "Target Group becomes Exposed.", "Free to use means someone else is the product."],
  ['Moon Landing Hoax', 'group', 3, 2, 5, '', "When recruited, gain 1 Influence.", "One giant leap, and a thousand unanswered questions."],
  ['Vaccine Microchip Scare', 'group', 3, 3, 4, '', "When recruited, gain 1 Influence.", "The side effects are listed. The real ones aren't."],
  ['Batsquatch', 'group', 6, 6, 6, 'Network', "When recruited, draw 1 card.", "Cast a print in the mud and the story writes itself."],
  ['Interdimensional Being Theory', 'group', 4, 5, 4, 'Cover', "Spend 1 Influence: remove Exposed from one of your Groups.", "Contact was made. Contact was covered up."],
  ['Lunar Base Alpha', 'operation', 3, 0, 0, '', "Look at an opponent's hand. Discard 1 card from it at random.", "The footage looks fake because it's old, not because it's fake. Probably."],
  ['Antarctic UFO Base', 'group', 6, 7, 7, '', "When recruited, target opponent discards 1 card.", "The truth is filed under a redaction."],
  ['Flat Earth Society', 'operation', 1, 0, 0, '', "Return one Group from your Archive to your hand.", "Somewhere past the ice wall, the map just stops."],
  ['Predictive Text Surveillance', 'group', 1, 1, 1, 'Expose', "When this deals combat damage, the opposing Group involved becomes Exposed.", "Free to use means someone else is the product."],
  ['Vanishing Point Highway', 'group', 4, 3, 5, '', "No additional ability.", "Somebody noticed. Nobody could unsee it after that."],
  ['Room 641A Tap', 'group', 3, 4, 4, 'Expose', "When this deals combat damage, the opposing Group involved becomes Exposed.", "Approved in a room with no windows."],
  ['Smart TV Listening Mode', 'group', 2, 2, 3, 'Cover', "Spend 1 Influence: remove Exposed from one of your Groups.", "It's not listening. It's just very, very good at guessing."],
  ['Atlantis', 'group', 3, 4, 5, '', "When recruited, draw 1 card.", "Buried for a reason nobody remembers, which is the point."],
  ['City of Aztlan Myth', 'group', 1, 2, 3, 'Network', "When recruited, draw 1 card.", "Lost, sunken, and somehow still on three separate maps."],
  ['5G Tower Rollout', 'group', 2, 2, 2, '', "When recruited, gain 1 Influence.", "Cure it and there's no repeat customer."],
  ['Ozark Howler', 'group', 6, 5, 6, '', "No additional ability.", "Cast a print in the mud and the story writes itself."],
  ['The Dyatlov Pass Incident', 'group', 2, 2, 3, '', "When recruited, target opponent discards 1 card.", "Somebody noticed. Nobody could unsee it after that."],
  ['The Vault at Fort Knox', 'group', 4, 4, 4, '', "When recruited, draw 1 card.", "The bailout was quiet. The bill wasn't."],
  ['Project Paperclip', 'group', 4, 3, 5, '', "When recruited, gain 1 Influence.", "Approved in a room with no windows."],
  ['Thule Society', 'operation', 2, 0, 0, '', "Target Group becomes Exposed.", "They meet in the room that isn't on the floor plan."],
  ['Rendlesham Forest Lights', 'operation', 2, 0, 0, '', "Target player discards 2 cards.", "Every light in the sky has a witness and a denial."],
  ['Third Eye Awakening', 'operation', 5, 0, 0, '', "Return one Group from your Archive to your hand.", "Older than the story that explains it."],
  ['Majestic 12', 'group', 3, 4, 4, 'Haste', "Can attack the turn it's recruited.", "The truth is filed under a redaction."],
  ['Black Lodge Circle', 'group', 3, 4, 5, '', "When recruited, draw 1 card.", "The minutes of this meeting were never taken."],
  ['Biometric Toll Booth', 'group', 4, 4, 5, 'Network', "When recruited, draw 1 card.", "The algorithm didn't choose this for you. Someone chose the algorithm."],
  ['Pope Lick Monster', 'wildcard', 4, 4, 4, '', "Dual-use: discard face-down for +1 Network Die (max 10), or recruit face-up as a weak Group.", "Blurry photo. Certain believer. No body ever found."],
  ['The Backmasked Message', 'wildcard', 2, 2, 2, '', "Dual-use: discard face-down for +1 Network Die (max 10), or recruit face-up as a weak Group.", "The mural doesn't explain itself. That's the point of murals."],
  ['License Plate Reader Grid', 'group', 4, 3, 6, '', "When recruited, gain 1 Influence.", "Free to use means someone else is the product."],
  ['Deepfake Propaganda Farm', 'group', 3, 3, 3, 'Fortify', "Prevent the first 2 damage this group would take.", "The algorithm didn't choose this for you. Someone chose the algorithm."],
  ['Honey Island Swamp Monster', 'group', 1, 1, 3, 'Cover', "Spend 1 Influence: remove Exposed from one of your Groups.", "The woods keep their own secrets."],
  ['VRIL Society Rite', 'group', 4, 4, 5, '', "No additional ability.", "Lost, sunken, and somehow still on three separate maps."],
  ['Fusion Center Data Grab', 'group', 5, 5, 5, '', "No additional ability.", "Somewhere there's a form for this. You'll never see it."],
  ['Nephilim', 'group', 2, 2, 3, '', "When recruited, gain 1 Influence.", "Older than the story that explains it."],
  ['Altamaha-ha', 'wildcard', 3, 3, 3, '', "Dual-use: discard face-down for +1 Network Die (max 10), or recruit face-up as a weak Group.", "Blurry photo. Certain believer. No body ever found."],
  ['Hollow Moon Theory', 'group', 1, 2, 2, 'Fortify', "Prevent the first 2 damage this group would take.", "Somewhere past the ice wall, the map just stops."],
  ['The Warren Commission Footnote', 'group', 2, 1, 2, '', "No additional ability.", "Somewhere there's a form for this. You'll never see it."],
  ['Mothman', 'group', 6, 5, 7, '', "When recruited, target opponent discards 1 card.", "Somewhere between folklore and fact, it walks."],
  ['Antarctica Ice Wall', 'group', 4, 5, 6, 'Haste', "Can attack the turn it's recruited.", "Somewhere past the ice wall, the map just stops."],
  ['Suppressed Free Energy Cure', 'group', 4, 3, 5, '', "When recruited, draw 1 card.", "Cure it and there's no repeat customer."],
  ['Grey Alien Handlers', 'group', 3, 3, 3, 'Pierce', "Excess combat damage carries over to the opponent's Life.", "Contact was made. Contact was covered up."],
  ['Search Result Shaping', 'referendum', 1, 0, 0, '', "Referendum. Each player votes (weight = Groups in play). If you win a majority, reveal all hands.", "The algorithm didn't choose this for you. Someone chose the algorithm."],
  ['Cookie Tracking Consortium', 'operation', 1, 0, 0, '', "Look at the top 3 cards of your deck. Add 1 to hand, Archive the rest.", "Free to use means someone else is the product."],
  ['The Engagement Algorithm', 'group', 1, 1, 2, '', "When recruited, gain 1 Influence.", "The algorithm didn't choose this for you. Someone chose the algorithm."],
  ['Sea Serpent Log Entry', 'operation', 3, 0, 0, '', "Return one Group from your Archive to your hand.", "Blurry photo. Certain believer. No body ever found."],
  ['Voice Assistant Wiretap', 'group', 4, 4, 4, '', "No additional ability.", "It's not listening. It's just very, very good at guessing."],
  ['Fresno Nightcrawlers', 'group', 1, 1, 3, '', "When recruited, gain 1 Influence.", "Cast a print in the mud and the story writes itself."],
  ['The Bavarian Circle', 'group', 3, 3, 4, 'Cover', "Spend 1 Influence: remove Exposed from one of your Groups.", "Every handshake means something, to someone."],
  ['The Committee of 300', 'group', 3, 3, 5, '', "When recruited, draw 1 card.", "They meet in the room that isn't on the floor plan."],
  ['Loch Ness Monster', 'group', 3, 4, 4, '', "When recruited, draw 1 card.", "Cast a print in the mud and the story writes itself."],
  ['The Unseen Hand', 'group', 3, 3, 3, '', "When recruited, target opponent discards 1 card.", "They meet in the room that isn't on the floor plan."],
  ['Algorithm Manipulation', 'group', 1, 1, 2, 'Network', "When recruited, draw 1 card.", "It's not listening. It's just very, very good at guessing."],
  ['Smart Meter Surveillance', 'group', 6, 5, 7, '', "When recruited, draw 1 card.", "It never happened. There's a memo confirming that."],
  ['Philadelphia Experiment', 'group', 2, 1, 3, '', "When recruited, target opponent discards 1 card.", "The mural doesn't explain itself. That's the point of murals."],
  ['Van Allen Belt Cover-Up', 'group', 4, 5, 4, 'Cover', "Spend 1 Influence: remove Exposed from one of your Groups.", "One giant leap, and a thousand unanswered questions."],
  ['Ariel School Sighting', 'operation', 5, 0, 0, '', "Remove Exposed from up to 1 of your Groups.", "Contact was made. Contact was covered up."],
  ['Wendigo Sighting', 'operation', 6, 0, 0, '', "Return one Group from your Archive to your hand.", "Blurry photo. Certain believer. No body ever found."],
  ['Third Shooter Theory', 'operation', 4, 0, 0, '', "All players lose 1 Life.", "The mural doesn't explain itself. That's the point of murals."],
  ['Skull and Bones', 'group', 3, 3, 4, 'Network', "When recruited, draw 1 card.", "They meet in the room that isn't on the floor plan."],
  ['The Eurodollar System', 'group', 1, 2, 1, '', "No additional ability.", "Money is just a story everyone agreed to believe."],
  ['Owlman of Cornwall', 'group', 2, 2, 3, '', "No additional ability.", "Somewhere between folklore and fact, it walks."],
  ['Ad Network Dossier', 'group', 2, 2, 4, 'Fortify', "Prevent the first 2 damage this group would take.", "It's not listening. It's just very, very good at guessing."],
  ['Secret Mars Colony', 'operation', 2, 0, 0, '', "Remove Exposed from up to 3 of your Groups.", "The footage looks fake because it's old, not because it's fake. Probably."],
  ['Zeta Reticuli Contact', 'group', 1, 1, 3, '', "When recruited, gain 1 Influence.", "Somewhere in the desert, something hums at night."],
  ['The Federal Reserve', 'group', 6, 6, 7, '', "When recruited, target opponent discards 1 card.", "Nobody elected the people who set the rate."],
  ['Beast of Bray Road', 'group', 4, 3, 4, '', "When recruited, gain 1 Influence.", "Somewhere between folklore and fact, it walks."],
  ['Suppressed Cancer Cure', 'group', 4, 5, 4, '', "When recruited, gain 1 Influence.", "The side effects are listed. The real ones aren't."],
  ['Order of the Black Sun', 'group', 3, 4, 3, '', "When recruited, draw 1 card.", "The minutes of this meeting were never taken."],
  ['The Kolbrin Bible', 'group', 5, 4, 6, '', "When recruited, target opponent discards 1 card.", "Older than the story that explains it."],
  ['The Miracle Supplement', 'operation', 4, 0, 0, '', "Remove Exposed from up to 2 of your Groups.", "The side effects are listed. The real ones aren't."],
  ['Mainstream Media', 'group', 4, 4, 5, '', "When recruited, draw 1 card.", "Free to use means someone else is the product."],
  ['Ritual at the Solstice', 'group', 2, 1, 3, 'Network', "When recruited, draw 1 card.", "Lost, sunken, and somehow still on three separate maps."],
  ['Trilateral Commission', 'group', 2, 1, 3, 'Haste', "Can attack the turn it's recruited.", "They meet in the room that isn't on the floor plan."],
  ['Fluoride', 'wildcard', 3, 3, 3, '', "Dual-use: discard face-down for +1 Network Die (max 10), or recruit face-up as a weak Group.", "The side effects are listed. The real ones aren't."],
  ['Exopolitics Council', 'group', 5, 6, 7, '', "When recruited, draw 1 card.", "The truth is filed under a redaction."],
  ['The Invisible College', 'operation', 4, 0, 0, '', "Look at an opponent's hand. Discard 1 card from it at random.", "They meet in the room that isn't on the floor plan."],
  ['Reptilian Shapeshifter Theory', 'group', 2, 2, 2, 'Haste', "Can attack the turn it's recruited.", "They came in peace. Allegedly."],
  ['Area 52', 'wildcard', 2, 2, 2, '', "Dual-use: discard face-down for +1 Network Die (max 10), or recruit face-up as a weak Group.", "Somewhere there's a form for this. You'll never see it."],
  ['Total Information Awareness', 'group', 1, 2, 1, '', "When recruited, draw 1 card.", "It never happened. There's a memo confirming that."],
  ['Sovereign Debt Trap', 'group', 2, 2, 2, '', "When recruited, draw 1 card.", "The bailout was quiet. The bill wasn't."],
  ['Dulce Base', 'group', 6, 7, 6, '', "When recruited, gain 1 Influence.", "Every light in the sky has a witness and a denial."],
  ['Ley Line Convergence', 'group', 1, 1, 2, '', "When recruited, gain 1 Influence.", "Older than the story that explains it."],
  ['Kraken Sighting', 'wildcard', 5, 5, 5, '', "Dual-use: discard face-down for +1 Network Die (max 10), or recruit face-up as a weak Group.", "The woods keep their own secrets."],
  ['Detox Tea Empire', 'operation', 2, 0, 0, '', "Target player discards 3 cards.", "Somebody patented the thing that was already free."],
  ['The Silent Brotherhood', 'group', 5, 5, 5, '', "When recruited, gain 1 Influence.", "Membership is by invitation. Existence is by denial."],
  ['Tunguska Event Theory', 'group', 2, 2, 3, '', "No additional ability.", "The mural doesn't explain itself. That's the point of murals."],
  ['Grand Architects Guild', 'wildcard', 3, 3, 3, '', "Dual-use: discard face-down for +1 Network Die (max 10), or recruit face-up as a weak Group.", "The minutes of this meeting were never taken."],
  ['Travis Walton Case', 'referendum', 3, 0, 0, '', "Referendum. Each player votes (weight = Groups in play). If you win a majority, the player with the most Life discards a card.", "The truth is filed under a redaction."],
  ['Ancient Order of the Nine Unknown', 'group', 2, 1, 3, 'Network', "When recruited, draw 1 card.", "They meet in the room that isn't on the floor plan."],
  ['Varginha Incident', 'group', 1, 1, 2, '', "No additional ability.", "They came in peace. Allegedly."],
  ['Battle of Los Angeles', 'group', 2, 1, 2, 'Haste', "Can attack the turn it's recruited.", "Somewhere in the desert, something hums at night."],
  ['Vril Society', 'group', 5, 5, 5, '', "No additional ability.", "Membership is by invitation. Existence is by denial."],
  ['Sovereign Wealth Backchannel', 'group', 4, 5, 5, 'Network', "When recruited, draw 1 card.", "Money is just a story everyone agreed to believe."],
  ['Sub-Biosphere Two', 'group', 5, 6, 6, '', "When recruited, gain 1 Influence.", "Somewhere past the ice wall, the map just stops."],
  ['Lake Champlain\'s Champ', 'group', 1, 2, 1, '', "When recruited, target opponent discards 1 card.", "Blurry photo. Certain believer. No body ever found."],
  ['Belgian UFO Wave', 'group', 6, 6, 7, 'Fortify', "Prevent the first 2 damage this group would take.", "Contact was made. Contact was covered up."],
  ['The Zodiac Cipher', 'group', 1, 1, 2, '', "No additional ability.", "The mural doesn't explain itself. That's the point of murals."],
  ['Star Chamber Society', 'group', 5, 6, 6, '', "When recruited, gain 1 Influence.", "The minutes of this meeting were never taken."],
  ['Remote Viewing Program', 'group', 3, 3, 3, 'Cover', "Spend 1 Influence: remove Exposed from one of your Groups.", "Approved in a room with no windows."],
  ['Metadata Collection Sweep', 'group', 3, 3, 5, '', "When recruited, target opponent discards 1 card.", "The algorithm didn't choose this for you. Someone chose the algorithm."],
  ['Council on Shadows', 'group', 1, 1, 3, '', "No additional ability.", "Every handshake means something, to someone."],
];

window.CARD_DATA = CARD_DATA;
